version: '3'
services:
  #PHP Service
  app:
    build:
      context: ./src/
      dockerfile: Dockerfile
      args:
        - USER_ID=1001
        - GROUP_ID=1001
    restart: always
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src/:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  #Nginx Service
  webserver:
    image: nginx:alpine
    restart: always
    ports:
      - 8091:80
      - 8443:443
    volumes:
      - ./src/:/var/www
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/logs:/var/log/nginx/

  #MySQL Service
  db:
    image: mariadb:alpine
    restart: always
    ports:
      - 33061:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql/:/var/lib/mysql/
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf

